# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 11_Append_Segment&Seg1.py
# Created on: 2020-10-08 10:44:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 11_Append_Segment&Seg1 <Segments__2_> <Segments> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Segments__2_ = arcpy.GetParameterAsText(0)
if Segments__2_ == '#' or not Segments__2_:
    Segments__2_ = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Segments" # provide a default value if unspecified

Segments = arcpy.GetParameterAsText(1)
if Segments == '#' or not Segments:
    Segments = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Segments" # provide a default value if unspecified

# Local variables:
NewData_shp = "C:\\DataCleanTemp\\NewData.shp"
seg1_shp = "C:\\DataCleanTemp\\seg1.shp"

# Process: Append
arcpy.Append_management("C:\\DataCleanTemp\\NewData.shp;C:\\DataCleanTemp\\seg1.shp", Segments, "NO_TEST", "SegNo \"SegNo\" true true false 2 Short 0 0 ,First,#,C:\\DataCleanTemp\\seg1.shp,SegNo,-1,-1;Boundty \"Boundty\" true true false 2 Short 0 0 ,First,#,C:\\DataCleanTemp\\seg1.shp,Boundty,-1,-1;ParFID \"ParFID\" true true false 4 Long 0 0 ,First,#,C:\\DataCleanTemp\\seg1.shp,ParFID,-1,-1;MBoundTy \"MBoundTy\" true true false 2 Short 0 0 ,First,#,C:\\DataCleanTemp\\seg1.shp,MBoundTy,-1,-1;ABoundTy \"ABoundTy\" true true false 2 Short 0 0 ,First,#,C:\\DataCleanTemp\\seg1.shp,ABoundTy,-1,-1;MarginName \"MarginName\" true true false 50 Text 0 0 ,First,#,C:\\DataCleanTemp\\seg1.shp,MarginName,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#", "")

