# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 13_Org_Construction_Delete.py
# Created on: 2020-10-08 10:46:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 13_Org_Construction_Delete <Segments> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Segments = arcpy.GetParameterAsText(0)
if Segments == '#' or not Segments:
    Segments = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Segments" # provide a default value if unspecified

# Local variables:
Construction = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Construction"
Construction__2_ = Construction

# Process: Delete Features
arcpy.DeleteFeatures_management(Construction)

