# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 1CreateFolder.py
# Created on: 2020-10-08 10:36:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
DataCleanTemp = "C:\\DataCleanTemp"
Delete_succeeded = "true"

# Process: Delete
arcpy.Delete_management(DataCleanTemp, "Folder")

