# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 17_parcelKey_generate.py
# Created on: 2020-10-09 14:57:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Parcel = "Parcel"
Parcel__3_ = Parcel

# Process: Calculate Field
arcpy.CalculateField_management(Parcel, "TEST_PK", "str( !GRIDS1!).ljust(9,'a') + str( !PARCELNO!).zfill(6) + str( !DISTRICT!).zfill(2) + str( !VDC! ).zfill(4) + str( !WARDNO!).zfill(2)", "PYTHON_9.3", "")

