# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 17_parcelKey_generate.py
# Created on: 2020-10-09 11:50:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Output_Feature_Class = ""
Parcel = "Parcel"
Parcel__2_ = Parcel

# Process: Calculate Field
arcpy.CalculateField_management("", "", "", "VB", "")

# Process: Add Field
arcpy.AddField_management(Data_Location + "\\Parcel", "Test_PK", "TEXT", "", "", "23", "", "NULLABLE", "NON_REQUIRED", "")

