# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 17a_merge_dummy_planning.py
# Created on: 2020-11-02 16:28:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import shutil



# Local variables:
# Local variables:
Folder_Location = "d:"
# Parcel = "Parcel"
Data_Location = "D:\\DissolveByParcelKey\\Dahachowk_1Kha.mdb"

# Process: Create Temp Folder to strore all processing intermediaries
DataCleanTemp = Folder_Location + "\\DataCleanTemp"
if (os.path.exists(DataCleanTemp)): # delete folder if exits, otherwise it causes error
    arcpy.Delete_management(DataCleanTemp, "Folder")
arcpy.CreateFolder_management(Folder_Location, "DataCleanTemp")
DataCleanTemp = Folder_Location + "\\DataCleanTemp"
arcpy.env.workspace = DataCleanTemp

# Generate parcelkey in mdb
arcpy.CalculateField_management(Data_Location + "\\Parcel", "PARCELKEY","str( !GRIDS1!).ljust(9,'a') + str( !PARCELNO!).zfill(6) + str( !DISTRICT!).zfill(2) + str( !VDC! ).zfill(4) + str( !WARDNO!).zfill(2)","PYTHON_9.3", "")

arcpy.FeatureClassToFeatureClass_conversion(Data_Location + "\\Parcel", DataCleanTemp, "Parcel.shp", "", "PARCELKEY \"PARCELKEY\" true true false 23 Text 0 0 ,First,#," + Data_Location + "\\Parcel,PARCELKEY,-1,-1;PARCELNO \"PARCELNO\" true true false 4 Long 0 0 ,First,#," + Data_Location + "\\Parcel,PARCELNO,-1,-1;DISTRICT \"DISTRICT\" true true false 2 Short 0 0 ,First,#," + Data_Location + "\\Parcel,DISTRICT,-1,-1;VDC \"VDC\" true true false 2 Short 0 0 ,First,#," + Data_Location + "\\Parcel,VDC,-1,-1;WARDNO \"WARDNO\" true true false 3 Text 0 0 ,First,#," + Data_Location + "\\Parcel,WARDNO,-1,-1;GRIDS1 \"GRIDS1\" true true false 9 Text 0 0 ,First,#," + Data_Location + "\\Parcel,GRIDS1,-1,-1;PARCELTY \"PARCELTY\" true true false 2 Short 0 0 ,First,#," + Data_Location + "\\Parcel,PARCELTY,-1,-1;ParcelNote \"ParcelNote\" true false false 200 Text 0 0 ,First,#," + Data_Location + "\\Parcel,ParcelNote,-1,-1;Shape_Leng \"Shape_Length\" false true true 8 Double 0 0 ,First,#," + Data_Location + "\\Parcel,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#," + Data_Location + "\\Parcel,Shape_Area,-1,-1", "")

Parcel = DataCleanTemp + "\\Parcel.shp"
# Process: Feature To Point
arcpy.FeatureToPoint_management(Parcel, DataCleanTemp + "\\ParcelCentroid.shp", "INSIDE")

# Process: Select Layer By Attribute
temp = "temp2"
arcpy.MakeFeatureLayer_management(Parcel, temp)
arcpy.SelectLayerByAttribute_management(temp, 'NEW_SELECTION', 'PARCELNO < 9000 AND PARCELNO <> 0')

# arcpy.SelectLayerByAttribute_management("tempInvert", "SWITCH_SELECTION")
# Process: Dissolve
arcpy.Dissolve_management(temp, DataCleanTemp + "\\ParcelDissolve.shp", "PARCELNO;DISTRICT;VDC;WARDNO;GRIDS1", "", "SINGLE_PART", "DISSOLVE_LINES")
arcpy.MakeFeatureLayer_management(Parcel, temp +"invert","PARCELNO >= 9000 OR PARCELNO = 0")
arcpy.SelectLayerByAttribute_management(temp + "invert", "NEW_SELECTION", "PARCELNO >= 9000 OR PARCELNO = 0")
arcpy.CopyFeatures_management(temp + "invert", DataCleanTemp + "\\ParcelRemain.shp")

# Join management
arcpy.SpatialJoin_analysis(DataCleanTemp + "\\ParcelDissolve.shp", DataCleanTemp + "\\ParcelCentroid.shp", DataCleanTemp + "\\NewJoinedData.shp", "JOIN_ONE_TO_ONE", "KEEP_ALL","PARCELNO \"PARCELNO\" true true false 10 Long 0 10 ,First,#," + DataCleanTemp + "\\ParcelDissolve.shp,PARCELNO,-1,-1;DISTRICT \"DISTRICT\" true true false 10 Long 0 10 ,First,#," + DataCleanTemp + "\\ParcelDissolve.shp,DISTRICT,-1,-1;VDC \"VDC\" true true false 10 Long 0 10 ,First,#," + DataCleanTemp + "\\ParcelDissolve.shp,VDC,-1,-1;WARDNO \"WARDNO\" true true false 3 Text 0 0 ,First,#," + DataCleanTemp + "\\ParcelDissolve.shp,WARDNO,-1,-1;GRIDS1 \"GRIDS1\" true true false 9 Text 0 0 ,First,#," + DataCleanTemp + "\\ParcelDissolve.shp,GRIDS1,-1,-1;PARCELKEY \"PARCELKEY\" true true false 23 Text 0 0 ,First,#," + DataCleanTemp + "\\ParcelCentroid.shp,PARCELKEY,-1,-1;PARCELTY \"PARCELTY\" true true false 10 Long 0 10 ,First,#," + DataCleanTemp + "\\ParcelCentroid,shp,PARCELTY,-1,-1;ParcelNote \"ParcelNote\" true true false 200 Text 0 0 ,First,#," + DataCleanTemp + "\\ParcelCentroid.shp,ParcelNote,-1,-1", "CONTAINS", "", "")

arcpy.Delete_management(Data_Location + "\\Parcel")
# Process: Copy Features
arcpy.CopyFeatures_management(BLANK84_Template + "\\Parcel", Data_Location + "\\Parcel", "", "0", "0", "0")
arcpy.Append_management(DataCleanTemp + "\\NewJoinedData.shp", Data_Location + "\\Parcel", "NO_TEST")
arcpy.Append_management(DataCleanTemp + "\\ParcelRemain.shp", Data_Location + "\\Parcel", "NO_TEST")

# Process: Append
arcpy.Append_management("D:\\neogeomat\\Documents\\ArcGIS\\Default.gdb\\Parcel_Dissolve5", Parcel__2_, "NO_TEST", "PARCELKEY \"PARCELKEY\" true true false 23 Text 0 0 ,First,#;PARCELNO \"PARCELNO\" true true false 4 Long 0 0 ,First,#,D:\\neogeomat\\Documents\\ArcGIS\\Default.gdb\\Parcel_Dissolve3,PARCELNO,-1,-1;DISTRICT \"DISTRICT\" true true false 2 Short 0 0 ,First,#,D:\\neogeomat\\Documents\\ArcGIS\\Default.gdb\\Parcel_Dissolve3,DISTRICT,-1,-1;VDC \"VDC\" true true false 2 Short 0 0 ,First,#,D:\\neogeomat\\Documents\\ArcGIS\\Default.gdb\\Parcel_Dissolve3,VDC,-1,-1;WARDNO \"WARDNO\" true true false 3 Text 0 0 ,First,#,D:\\neogeomat\\Documents\\ArcGIS\\Default.gdb\\Parcel_Dissolve3,WARDNO,-1,-1;GRIDS1 \"GRIDS1\" true true false 9 Text 0 0 ,First,#,D:\\neogeomat\\Documents\\ArcGIS\\Default.gdb\\Parcel_Dissolve3,GRIDS1,-1,-1;PARCELTY \"PARCELTY\" true true false 2 Short 0 0 ,First,#;ParcelNote \"ParcelNote\" true false false 200 Text 0 0 ,First,#;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#;TEST_PK \"TEST_PK\" true true false 23 Text 0 0 ,First,#;circularity \"circularity\" true true false 4 Float 0 0 ,First,#", "")

