# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 18_compact_mdb.py
# Created on: 2020-10-09 13:11:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Dadapauwa_2ka1_mdb = "D:\\integrate free sheet\\using_coverage_method\\Dadapauwa_2ka1.mdb"
Dadapauwa_2ka1_mdb__2_ = Dadapauwa_2ka1_mdb

# Process: Compact
arcpy.Compact_management(Dadapauwa_2ka1_mdb)

