# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2_CopyParcelToParcel1.py
# Created on: 2020-10-08 10:40:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 2_CopyParcelToParcel1 <Parcel__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Parcel__2_ = arcpy.GetParameterAsText(0)
if Parcel__2_ == '#' or not Parcel__2_:
    Parcel__2_ = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel" # provide a default value if unspecified

# Local variables:
Parcel1_shp = Parcel__2_
DataCleanTemp = "C:\\DataCleanTemp"

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(Parcel__2_, DataCleanTemp, "Parcel1.shp", "", "PARCELKEY \"PARCELKEY\" true true false 23 Text 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,PARCELKEY,-1,-1;PARCELNO \"PARCELNO\" true true false 4 Long 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,PARCELNO,-1,-1;DISTRICT \"DISTRICT\" true true false 2 Short 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,DISTRICT,-1,-1;VDC \"VDC\" true true false 2 Short 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,VDC,-1,-1;WARDNO \"WARDNO\" true true false 3 Text 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,WARDNO,-1,-1;GRIDS1 \"GRIDS1\" true true false 9 Text 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,GRIDS1,-1,-1;PARCELTY \"PARCELTY\" true true false 2 Short 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,PARCELTY,-1,-1;ParcelNote \"ParcelNote\" true false false 200 Text 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,ParcelNote,-1,-1;Shape_Leng \"Shape_Length\" false true true 8 Double 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#,C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel,Shape_Area,-1,-1", "")

