# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2_EliminateAndCopyParcelToParcel1.py
# Created on: 2020-10-09 13:39:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
Dadapauwa_2ka1_mdb = "D:\\integrate free sheet\\using_coverage_method\\Dadapauwa_2ka1.mdb"
Dadapauwa_2ka1_mdb__2_ = Dadapauwa_2ka1_mdb
Output_Feature_Class = ""

# Process: Compact
arcpy.Compact_management(Dadapauwa_2ka1_mdb)

# Process: Eliminate Polygon Part
arcpy.EliminatePolygonPart_management("", Output_Feature_Class, "AREA", "0.005 SquareMeters", "0", "ANY")

