# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 7a_Append_Parcel&NewData.py
# Created on: 2020-10-08 10:43:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 7a_Append_Parcel&NewData <Parcel__4_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Parcel__4_ = arcpy.GetParameterAsText(0)
if Parcel__4_ == '#' or not Parcel__4_:
    Parcel__4_ = "Parcel" # provide a default value if unspecified

# Local variables:
NewData_shp = "C:\\DataCleanTemp\\NewData.shp"
Parcel__2_ = "Parcel"

# Process: Append
arcpy.Append_management("C:\\DataCleanTemp\\NewData.shp", Parcel__2_, "NO_TEST", "PARCELKEY \"PARCELKEY\" true true false 23 Text 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,PARCELKEY,-1,-1;PARCELNO \"PARCELNO\" true true false 4 Long 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,PARCELNO,-1,-1;DISTRICT \"DISTRICT\" true true false 2 Short 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,DISTRICT,-1,-1;VDC \"VDC\" true true false 2 Short 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,VDC,-1,-1;WARDNO \"WARDNO\" true true false 3 Text 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,WARDNO,-1,-1;GRIDS1 \"GRIDS1\" true true false 9 Text 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,GRIDS1,-1,-1;PARCELTY \"PARCELTY\" true true false 2 Short 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,PARCELTY,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,Shape_Area,-1,-1;ParcelNote \"ParcelNote\" true false false 200 Text 0 0 ,First,#,C:\\DataCleanTemp\\NewData.shp,ParcelNote,-1,-1", "")

