# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 7b_AddField.py
# Created on: 2020-10-08 10:43:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Parcel = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Parcel"
Parcel__2_ = Parcel
Parcel__9_ = Parcel__2_

# Process: Add Field (3)
arcpy.AddField_management(Parcel, "Ids", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Parcel__2_, "IDS", "[OBJECTID]", "VB", "")

