# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 9_Org_Segment_Delete.py
# Created on: 2020-10-08 10:44:01.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 9_Org_Segment_Delete <Segments> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Segments = arcpy.GetParameterAsText(0)
if Segments == '#' or not Segments:
    Segments = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Segments" # provide a default value if unspecified

# Local variables:
Segments__2_ = Segments

# Process: Delete Features
arcpy.DeleteFeatures_management(Segments)

