# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 14_Copy_Construction_form_Blank84.py
# Created on: 2020-10-08 10:46:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Construction = "D:\\LIS_SYSTEM\\LIS_Spatial_Data_Templates\\BLANK84.mdb\\Construction"
Construction__2_ = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Construction"
Segments__3_ = "D:\\LIS_SYSTEM\\LIS_Spatial_Data_Templates\\BLANK84.mdb\\Segments"

# Process: Copy Features
arcpy.CopyFeatures_management(Construction, Construction__2_, "", "0", "0", "0")

