# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 15_Append_Construction&Cons1.py
# Created on: 2020-10-08 10:47:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 15_Append_Construction&Cons1 <Construction__2_> <Construction> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Construction__2_ = arcpy.GetParameterAsText(0)
if Construction__2_ == '#' or not Construction__2_:
    Construction__2_ = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Construction" # provide a default value if unspecified

Construction = arcpy.GetParameterAsText(1)
if Construction == '#' or not Construction:
    Construction = "C:\\Users\\DELL\\Desktop\\Coverage_Create\\102-1139-22.mdb\\Construction" # provide a default value if unspecified

# Local variables:
Cons1_shp = "C:\\DataCleanTemp\\Cons1.shp"

# Process: Append
arcpy.Append_management("C:\\DataCleanTemp\\Cons1.shp", Construction, "NO_TEST", "ParFID \"ParFID\" true true false 4 Long 0 0 ,First,#,C:\\DataCleanTemp\\Cons1.shp,ParFID,-1,-1;ConsTy \"ConsTy\" true true false 2 Short 0 0 ,First,#;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#,C:\\DataCleanTemp\\Cons1.shp,Shape_Area,-1,-1", "")

