# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 1CreateFolder.py
# Created on: 2020-10-08 10:38:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Folder_Location = "c:\\"
DataCleanTemp = Folder_Location

# Process: Create Folder
arcpy.CreateFolder_management(Folder_Location, "DataCleanTemp")

