# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 5_CopyPolygonFromCoverage.py
# Created on: 2020-10-08 10:41:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
cov1_polygon = "C:\\DataCleanTemp\\cov1\\polygon"
CleanPoly_shp = "C:\\DataCleanTemp\\CleanPoly.shp"

# Process: Copy Features
arcpy.CopyFeatures_management(cov1_polygon, CleanPoly_shp, "", "0", "0", "0")

