# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 6_SpatialJoin_Paecel&Parcel1.py
# Created on: 2020-10-08 10:42:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
CleanPoly_shp = "C:\\DataCleanTemp\\CleanPoly.shp"
Parcel1_shp = "C:\\DataCleanTemp\\Parcel1.shp"
NewData_shp = "C:\\DataCleanTemp\\NewData.shp"

# Process: Spatial Join
arcpy.SpatialJoin_analysis(CleanPoly_shp, Parcel1_shp, NewData_shp, "JOIN_ONE_TO_ONE", "KEEP_ALL", "AREA \"AREA\" true true false 19 Double 0 0 ,First,#,C:\\DataCleanTemp\\CleanPoly.shp,AREA,-1,-1;PERIMETER \"PERIMETER\" true true false 19 Double 0 0 ,First,#,C:\\DataCleanTemp\\CleanPoly.shp,PERIMETER,-1,-1;COV1_ \"COV1_\" true true false 10 Long 0 10 ,First,#,C:\\DataCleanTemp\\CleanPoly.shp,COV1_,-1,-1;COV1_ID \"COV1_ID\" true true false 10 Long 0 10 ,First,#,C:\\DataCleanTemp\\CleanPoly.shp,COV1_ID,-1,-1;PARCELKEY \"PARCELKEY\" true true false 23 Text 0 0 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,PARCELKEY,-1,-1;PARCELNO \"PARCELNO\" true true false 10 Long 0 10 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,PARCELNO,-1,-1;DISTRICT \"DISTRICT\" true true false 5 Long 0 5 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,DISTRICT,-1,-1;VDC \"VDC\" true true false 5 Long 0 5 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,VDC,-1,-1;WARDNO \"WARDNO\" true true false 3 Text 0 0 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,WARDNO,-1,-1;GRIDS1 \"GRIDS1\" true true false 9 Text 0 0 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,GRIDS1,-1,-1;PARCELTY \"PARCELTY\" true true false 5 Long 0 5 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,PARCELTY,-1,-1;ParcelNote \"ParcelNote\" true true false 200 Text 0 0 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,ParcelNote,-1,-1;Shape_Leng \"Shape_Leng\" true true false 19 Double 0 0 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,Shape_Leng,-1,-1;Shape_Area \"Shape_Area\" true true false 19 Double 0 0 ,First,#,C:\\DataCleanTemp\\Parcel1.shp,Shape_Area,-1,-1", "INTERSECT", "", "")

